### ISSUE TITLE
I want a discord plugin

### ISSUE THREAD

**Issue by AlexisTrouve** [Baduit/YololTranslator#1]
It can be interesting to have the YololTranslator as a discord plugin.

**Comment by Baduit** [comment]
An online Rest API should arrive soon then the website, but after that why not make a discord plugin.

**Comment by Baduit** [comment]
Finally i have seen that creating a discord bot way easier than i thought, so it is now available. 
Here the link to add it to your discord server [https://discordapp.com/api/oauth2/authorize?client_id=536250577051451402&permissions=2048&redirect_uri=https%3A%2F%2Fdiscordapp.com%2Fapi%2Foauth2%2Fauthorize%3Fclient_id%3D536250577051451402%26redirect_uri%3Dhttps%253A%252F%252Fdiscordapp.com%252Foauth2%252Fauthorize%253F%2526client_id%253D53625057705145140&scope=bot](url)
